# Generated by Django 5.1 on 2024-11-08 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('position', models.PositiveIntegerField(null=True)),
                ('note', models.TextField(blank=True, max_length=150, null=True)),
                ('code', models.CharField(editable=False, max_length=6, unique=True)),
                ('state', models.CharField(choices=[('waiting', 'Waiting'), ('serving', 'Serving'), ('completed', 'Completed')], default='waiting', max_length=10)),
                ('service_started_at', models.DateTimeField(blank=True, null=True)),
                ('service_completed_at', models.DateTimeField(blank=True, null=True)),
                ('waited', models.PositiveIntegerField(default=0)),
                ('visits', models.PositiveIntegerField(default=1)),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.queue')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.queue')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participant.participant')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantParticipant',
            fields=[
                ('participant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='participant.participant')),
                ('table_served', models.CharField(blank=True, max_length=20, null=True)),
                ('party_size', models.PositiveIntegerField(default=1)),
                ('seating_preference', models.CharField(choices=[('first_available', 'First Available'), ('indoor', 'Indoor'), ('outdoor', 'Outdoor')], default='first_available', max_length=20)),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.table')),
            ],
            bases=('participant.participant',),
        ),
    ]
