# Generated by Django 5.1 on 2024-10-11 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={},
        ),
        migrations.RemoveField(
            model_name='participant',
            name='status',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='queue',
            name='code',
            field=models.CharField(default='ABC123', editable=False, max_length=6, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='queue',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='queue',
            name='estimated_wait_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_no',
            field=models.CharField(default='0000000000', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('creator', 'Queue Creator'), ('participant', 'Participant')], default='creator', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participant',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='position',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='queue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queue_manager.queue'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='queue',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='queue',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
