# Generated by Django 5.1 on 2024-10-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_manager', '0002_alter_queue_estimated_wait_time_per_turn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='estimated_wait_time_per_turn',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
