# Generated by Django 5.1 on 2024-10-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_manager', '0002_alter_participant_options_remove_participant_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='participant',
            name='position',
            field=models.PositiveIntegerField(),
        ),
    ]
