# Generated by Django 5.1 on 2024-11-08 14:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=60)),
                ('open_time', models.DateTimeField(blank=True, null=True)),
                ('close_time', models.DateTimeField(blank=True, null=True)),
                ('estimated_wait_time_per_turn', models.PositiveIntegerField(default=0)),
                ('average_service_duration', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('is_closed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('busy', 'Busy'), ('full', 'Full')], default='normal', max_length=10)),
                ('category', models.CharField(choices=[('restaurant', 'Restaurant'), ('general', 'General'), ('hospital', 'Hospital'), ('bank', 'Bank'), ('service center', 'Service center')], max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='queue_logos/')),
                ('completed_participants_count', models.PositiveIntegerField(default=0)),
                ('code', models.CharField(editable=False, max_length=6, unique=True)),
                ('authorized_user', models.ManyToManyField(blank=True, related_name='queues', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('empty', 'Empty'), ('busy', 'Busy'), ('unavailable', 'Unavailable')], default='empty', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantQueue',
            fields=[
                ('queue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='manager.queue')),
                ('has_outdoor', models.BooleanField(default=False)),
            ],
            bases=('manager.queue',),
        ),
    ]
