# Generated by Django 5.1.3 on 2024-11-30 14:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=255)),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('estimated_wait_time_per_turn', models.PositiveIntegerField(default=0)),
                ('average_service_duration', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('is_closed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('busy', 'Busy'), ('full', 'Full')], default='normal', max_length=10)),
                ('category', models.CharField(choices=[('general', 'General'), ('restaurant', 'Restaurant'), ('hospital', 'Hospital'), ('bank', 'Bank')], max_length=20)),
                ('logo', models.CharField(blank=True, max_length=500, null=True)),
                ('completed_participants_count', models.PositiveIntegerField(default=0)),
                ('code', models.CharField(editable=False, max_length=12, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('distance_from_user', models.FloatField(blank=True, null=True)),
                ('tts_notifications_enabled', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('unavailable', 'Unavailable')], default='available', max_length=15)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='QueueLineLength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('line_length', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='profile_images/')),
                ('google_picture', models.URLField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BankQueue',
            fields=[
                ('queue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='manager.queue')),
            ],
            bases=('manager.queue',),
        ),
        migrations.CreateModel(
            name='HospitalQueue',
            fields=[
                ('queue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='manager.queue')),
            ],
            bases=('manager.queue',),
        ),
        migrations.CreateModel(
            name='RestaurantQueue',
            fields=[
                ('queue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='manager.queue')),
            ],
            bases=('manager.queue',),
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='manager.resource')),
                ('service_type', models.CharField(choices=[('account_services', 'Account Services'), ('loan_services', 'Loan Services'), ('investment_services', 'Investment Services'), ('customer_support', 'Customer Support')], default='account_service', max_length=100)),
            ],
            bases=('manager.resource',),
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='manager.resource')),
                ('specialty', models.CharField(choices=[('cardiology', 'Cardiology'), ('neurology', 'Neurology'), ('orthopedics', 'Orthopedics'), ('dermatology', 'Dermatology'), ('pediatrics', 'Pediatrics'), ('general', 'General Medicine'), ('emergency', 'Emergency'), ('psychiatry', 'Psychiatry'), ('surgery', 'Surgery'), ('oncology', 'Oncology')], default='general', max_length=100)),
            ],
            bases=('manager.resource',),
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='manager.resource')),
            ],
            bases=('manager.resource',),
        ),
    ]
