# Generated by Django 5.1.3 on 2024-11-30 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0001_initial'),
        ('participant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_assignment', to='participant.participant'),
        ),
        migrations.AddField(
            model_name='resource',
            name='queue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.queue'),
        ),
        migrations.AddField(
            model_name='queuelinelength',
            name='queue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.queue'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankqueue',
            name='resources',
            field=models.ManyToManyField(to='manager.counter'),
        ),
        migrations.AddField(
            model_name='hospitalqueue',
            name='resources',
            field=models.ManyToManyField(to='manager.doctor'),
        ),
        migrations.AddField(
            model_name='restaurantqueue',
            name='resources',
            field=models.ManyToManyField(to='manager.table'),
        ),
        migrations.AlterUniqueTogether(
            name='resource',
            unique_together={('name', 'queue')},
        ),
    ]
